server:
  port: 8081

logging:
  level:
    root: INFO
    com.ilogics.application.pharmacy: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://144.91.78.1:5432/ilogics
    username: ilogics
    password: ilogics
    # HikariCP settings
    hikari:
      #60 sec
      connection-timeout: 60000
      # max 5
      maximum-pool-size: 5

root:
  url: /v1/pharmacy

